// Market Actions
export const UPDATE_MARKET = "UPDATE_MARKET";
export const CREATE_MARKET = " CREATE_MARKET ";
export const UPDATE_MARKET_DETAILS = " UPDATE_MARKET_DETAILS";
export const GET_MARKET_BY_OWNER_ID = "GET_MARKET_BY_OWNER_ID";
export const GET_MARKET_PROFILE_PHOTO = "  GET_MARKET_PROFILE_PHOTO";

// User Actions
export const LOGOUT = "LOGOUT";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
